#!/usr/bin/env python

import os
import requests
import sys

def main():
    execution_url = os.environ['PTERO_WORKFLOW_EXECUTION_URL']

    execution_data = requests.get(execution_url).json()
    print execution_data
    inputs = execution_data['inputs']

    patch_data = {
        'outputs': inputs
    }
    if requests.patch(execution_url, json=patch_data).status_code != 200:
        sys.exit(2)

    # This tests that outputs cannot be set more than once
    patch_data = {
        'outputs': {'foo': 'bar'}
    }
    if requests.patch(execution_url, json=patch_data).status_code != 409:
        sys.exit(3)

    sys.exit(os.EX_OK)

if __name__ == "__main__":
    main()
