#!/usr/bin/env bash
set -e
set -o pipefail
set -o nounset

trap 'exit 1' SIGINT SIGTERM

readonly LOG_BASE=var/log
readonly HONCHO_LOG=${LOG_BASE}/honcho.out
declare DEVSERVER_PID
EXIT_CODE=0


function collect_test_names_dry_run() {
  local FAILURES=$(nosetests --collect-only -v 2>&1 |grep '^Failure:')
  if ! test -z "${FAILURES}"; then
      printf "Failed to collect tests to run:\n%s" ${FAILURES}
      exit 1
  fi
}

function capture_test_log() {
  local INITIAL_LOG_LENGTH=$1
  local TEST_NAME=$2
  local FINAL_LOG_LENGTH=$(wc -l ${HONCHO_LOG}|awk '{ print $1 }')
  tail -n $(expr ${FINAL_LOG_LENGTH} - ${INITIAL_LOG_LENGTH}) ${HONCHO_LOG} \
      > ${LOG_BASE}/${TEST_NAME}.log
}

function collect_test_names() {
  echo "$(nosetests --collect-only -v 2>&1 |grep 'test_'|cut -d\( -f2|cut -d\) -f1)"
}

function collect_number_of_tests() {
  echo "$(collect_test_names)" | wc -l
}

function collect_number_of_unique_tests() {
  echo "$(collect_test_names | uniq)" | wc -l
}

function run_tests() {
  echo "Found $(collect_number_of_tests) tests in $(collect_number_of_unique_tests) test classes to run"

  local TEST_NAMES=$(collect_test_names | uniq)
  for TEST_NAME in ${TEST_NAMES}; do
    local INITIAL_LOG_LENGTH=$(wc -l ${HONCHO_LOG}|awk '{ print $1 }')
    local NOSE_TEST_NAME=$(                     \
        perl -e '$ARGV[0] =~ s/\.([^.]+)$/:$1/; \
        print $ARGV[0]' ${TEST_NAME})

    printf "%s ... " ${NOSE_TEST_NAME}
    if coverage run $(which nosetests) -q ${NOSE_TEST_NAME} 2> /dev/null; then
      printf "OK\n"
      capture_test_log ${INITIAL_LOG_LENGTH} ${TEST_NAME}
    else
      capture_test_log ${INITIAL_LOG_LENGTH} ${TEST_NAME}
      printf "FAIL\n"
      cat ${LOG_BASE}/${TEST_NAME}.log
      EXIT_CODE=1
    fi

  done
}

collect_test_names_dry_run
run_tests
exit $EXIT_CODE
