#!/usr/bin/env python

import os
import requests
import sys

def main():
    execution_url = os.environ['PTERO_WORKFLOW_EXECUTION_URL']
    print "Found PTERO_WORKFLOW_EXECUTION_URL = %s" % execution_url

    execution_data = requests.get(execution_url).json()
    print "Found execution_data from GET request = %s" % execution_data
    inputs = execution_data['inputs']

    submit_url = os.environ['PTERO_WORKFLOW_SUBMIT_URL']
    print "Found PTERO_WORKFLOW_SUBMIT_URL = %s" % submit_url
    workflow_data = inputs['workflow_data']
    workflow_data['parentExecutionUrl'] = execution_url

    post_response = requests.post(submit_url, json=workflow_data)
    if (post_response.status_code != 201):
        print "Expected status_code 201, but recieved %s instead." % post_response.status_code
        sys.exit(3)
    workflow_url = post_response.headers['location']

    updated_execution_data = requests.get(execution_url).json()
    if 'childWorkflowUrls' not in updated_execution_data:
        print "Expected 'childWorkflowUrl' in response to GET %s." % execution_url
        sys.exit(3)
    if updated_execution_data['childWorkflowUrls'] != [workflow_url]:
        print "Expected 'childWorkflowUrl' to be '%s'" % str([workflow_url])
        sys.exit(3)

    sys.exit(os.EX_OK)

if __name__ == "__main__":
    main()
